### PR TITLE
Starting graph algebra

### PR DESCRIPTION
**Pull request by Mec-iS**
First PR for #261

Please suggest how to proceed. For now I have implemented conversions to `numpy.array`, which metrics/algorithms would you like to see computed?

Please consider writing notebooks that use these functionalities.

cc: @tomaarsen @ceteri @SultanOrazbayev

### CODE REVIEW

**Review by ceteri — APPROVED** [review]
Looks good!

**Review by ceteri — CHANGES_REQUESTED** [review]
This is looking good!
Two questions:

1. Dependencies `numpy`, `sklearn`, `skn` are pegged to specific point releases. Do they need to be? Previously, this caused lots of compatibility problems since people on different platforms (e.g., Windows) working on different specific use cases (other dependencies) ran into many conflicts, since they required specific point releases.  Is there a way to use ranges instead?
2. For network analysis, is there any trade-off comparison of using these approaches (e.g., with skn) versus using NetworkX?  If we use NetworkX then we can often pickup paths for better performance using GPUs (RAPIDS) and scale.

**Comment by Mec-iS** [comment]
1. These are the current dependencies situation: `scikit-learn` has to be pinned to current stable version 1 as when the current nightly version 2 will come out there may be breaking changes, `skn` requires `scipy==1.23.0`. For Windows users, may be useful to suggest using Anaconda or implement the usage of `poetry` that I was thinking about implementing.
2. Yes you are right. I thought to use `skn` as the API is very user-friendly and similar to the very popular `scikit-learn`, in terms of GPU support `networkx` is probably better.

I will open issues for some of those.

**Comment by Mec-iS** [comment]
@ceteri #271

**Pull request merged**
