### PR TITLE
Pyproject poetry mid update

### PR DESCRIPTION
**Pull request by jake-aft**

### CODE REVIEW

**Comment by jake-aft** [comment]
@ceteri here is my WIP for the poetry conversion.  pyproject.toml is in good order, I have not tested the package build as yet.

**Comment by jake-aft** [comment]
I also have a Pipfile and have updated the README to include the new install instructions to install with pipenv and poetry. If it useful for you to take the pyproject.toml, and I'll do a diff merge request for these updates later.

**Comment by ceteri** [comment]
Thank you kindly @jake-aft 
There are some outstanding issues in the comment threads on #275 and #294 

The wheel builds just find, goes into PyPi fine, and I can run sample code with it from a download in a new env.

The source dist is the problem, currently the build tools seem to ignore commands to exclude/prune the unneeded directories – particularly the `tests/` subdirectory which has ginormous benchmarks files for all of RDF and SPARQL.

**Comment by Mec-iS** [comment]
please complete the issue's description

**Comment by jake-aft** [comment]
@ceteri and @Mec-iS I am splitting this into two PRS 
POETRY AND PIPENV INSTALL
https://github.com/DerwenAI/kglab/pull/299

I can follow up with the poetry build updates/PR it seems to work well and have not had the exclude / package size issues you were having with flint. 

@ceteri please cancel this PR whenever you no longer need it as a reference.

**Comment by jake-aft** [comment]
This is split into two separate PRs
*Poetry and pipenv install:* https://github.com/DerwenAI/kglab/pull/295
*Poetry build:* https://github.com/DerwenAI/kglab/pull/300

**Pull request closed without merging**
