### PR TITLE
Add morph-kgc materialize

### PR DESCRIPTION
**Pull request by Mec-iS**
Please try `pytest --nbmake examples/ex6_2.ipynb`

### New expected behaviour
see https://github.com/DerwenAI/kglab/issues/108#issuecomment-1048445124

### Change logs

Add the `materialized()` method to `kglab.py`.
Add an example for it at `ex6_2.ipynb`

Add docstring at the top of `kglab.py`

### CODE REVIEW

**Comment by ArenasGuerreroJulian** [comment]
Hi @Mec-iS ,

Keep in mind that `materialize` can also receive a config in the form of a string and not a path. E.g.:

```
config = """
            [DataSource1]
            mappings=/path/to/mapping/mapping_file.rml.ttl
            db_url=mysql+pymysql://user:password@localhost:3306/db_name
         """

graph = morph_kgc.materialize(config)
```

see [doc](https://github.com/oeg-upm/Morph-KGC/wiki/Usage#library)

**Comment by Mec-iS** [comment]
yes thanks. I am just doing it step by step to test the integration.

**Comment by Mec-iS** [comment]
It looks like the file we currently use as test `recipe.ttl` has a faulty header according to `morph-kgc`

```
~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/args_parser.py in load_config_from_argument(config_entry)
     86     config = Config(interpolation=ExtendedInterpolation())
     87     if os.path.isfile(config_entry):
---> 88         config.read(config_entry)
     89     else:
     90         # it is a string

MissingSectionHeaderError: File contains no section headers.
file: '/home/lorenzo/drwn/kglab/dat/recipes.ttl', line: 1
'@prefix dct:  <http://purl.org/dc/terms/> .\n'
```

**Comment by ArenasGuerreroJulian** [comment]
Hi @Mec-iS ,

`materialize` expects a `.ini` file, not a `.ttl`. For testing morph-kgc with recipe you would need to define an RML mapping from [recipes.csv](https://github.com/DerwenAI/kglab/blob/main/dat/recipes.csv) to [recipes.ttl](https://github.com/DerwenAI/kglab/blob/main/dat/recipes.ttl). And prepare the `config.ini`.

Other option is to use one of the examples in the morph-kgc repo e.g. the [`json-example`](https://github.com/oeg-upm/morph-kgc/tree/main/examples/json-example)

**Comment by Mec-iS** [comment]
Thanks for the feedback. I am trying to establish a baseline.
I have added a default `ini` as taken from [here](https://github.com/oeg-upm/morph-kgc/blob/main/examples/configuration-file-examples/default_config.ini).

Now the error:
```
~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/__init__.py in materialize(config)
     24     setup_oracle(config)
     25 
---> 26     mappings_df = retrieve_mappings(config)
     27     subject_maps_df = get_subject_maps(mappings_df)
     28     mapping_partitions = [group for _, group in mappings_df.groupby(by='mapping_partition')]

~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/engine.py in retrieve_mappings(config)
     26 
     27         start_time = time.time()
---> 28         mappings = mappings_parser.parse_mappings()
     29         logging.info('Mappings processed in ' + get_delta_time(start_time) + ' seconds.')
     30 

~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/mapping/mapping_parser.py in parse_mappings(self)
    293 
    294     def parse_mappings(self):
--> 295         self._get_from_r2_rml()
    296         self._preprocess_mappings()
    297         self._infer_datatypes()

~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/mapping/mapping_parser.py in _get_from_r2_rml(self)
    323         else:
    324             for section_name in self.config.get_data_sources_sections():
--> 325                 data_source_mappings_df = self._parse_data_source_mapping_files(section_name)
    326                 self.mappings_df = pd.concat([self.mappings_df, data_source_mappings_df])
    327 

~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/mapping/mapping_parser.py in _parse_data_source_mapping_files(self, section_name)
    368 
    369         # convert the SPARQL result set with the parsed mappings to DataFrame
--> 370         return _transform_mappings_into_dataframe(mapping_query_results, join_query_results, section_name)
    371 
    372     def _preprocess_mappings(self):

~/drwn/.venv/lib/python3.8/site-packages/morph_kgc/mapping/mapping_parser.py in _transform_mappings_into_dataframe(mapping_query_results, join_query_results, section_name)
    229     join_conditions_dict = _get_join_object_maps_join_conditions(join_query_results)
    230     # map the dict with the join conditions to the mapping rules in the DataFrame
--> 231     source_mappings_df['join_conditions'] = source_mappings_df['object_map'].map(join_conditions_dict)
    232     # needed for later hashing the dataframe
    233     source_mappings_df['join_conditions'] = source_mappings_df['join_conditions'].where(

~/drwn/.venv/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3456             if self.columns.nlevels > 1:
   3457                 return self._getitem_multilevel(key)
-> 3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):
   3460                 indexer = [indexer]

~/drwn/.venv/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'object_map'
```

**Comment by ceteri** [comment]
> MissingSectionHeaderError: File contains no section headers.
> file: '/home/lorenzo/drwn/kglab/dat/recipes.ttl', line: 1
> '@prefix dct:  <http://purl.org/dc/terms/> .\n'
> ```

Does that `File contains no section headers` message refers to the input `.ini` file, and not the `recipes.ttl` file?
There's no particular definition of "section headers" in RDF files.

We've used `recipes.ttl` with a number of different platforms and validators, with no errors.

It does go into `@prefix` definitions without specifying the optional `@base` – if that may have triggered a warning?

**Comment by ceteri** [comment]
> In the `kglab` repository we already have both formats, do you mean something like [this](https://pypi.org/project/triplify-csv/)?

For this integration, the biggest use cases will be to formalize how sources from SQL, CSV, etc., can be ingested into an RDF graph. We're not looking at means to _translate_ between serialization formats, e.g., go between CSV and TTL.

While there are means of importing CSV already in `kglab`, through the `csvwlib` integration, this integration with `morph-kgc` would provide superior means, and also ways to parallelize and make these kinds of inputs much more efficient.

In the most immediate use cases (for our colleagues in Madrid and Murcia) they have many smaller SQL databases and thousands of CSV files, so there are performance issues at scale for ingest, and Morph can really help! :)

**Comment by ceteri** [comment]
Looks great @Mec-iS !!

**Review by ceteri — APPROVED** [review]
Looks great @Mec-iS !!

**Comment by Mec-iS** [comment]
@ceteri

i don't think this is finished because the mapping RML file is missing (what in the morph-kgl documentation has extension `.rml.ttl`). The ttl file is not enough to make it work, there should be a way to generate the RML mapping from a ttl or CSV.

**Comment by ceteri** [comment]
@Mec-iS 
Thank you, I've reverted this merge.

Was just trying examples within my own branch and ran into problems with the `csv-examples` in Morph, when running locally.

Instead of applying an RML mapping to a TTL file as input, how about if we show an example in the tutorial notebook that takes 2 simple CSV files?  This is a general pattern among users, where they already have node+edge files as CSV.

@ArenasGuerreroJulian do you have an simple RML for CSV examples?  Something like the proverbial _minimum viable_ that would show nodes and edges for a simple graph?  That would help for our community, where they aren't familiar with RML yet.  For example, how about something like this? <https://rml.io/yarrrml/tutorial/getting-started/#example>

**Comment by ceteri** [comment]
@Mec-iS here's a branch with preparations for a new release, for the `morph-kgc` integration:
<https://github.com/DerwenAI/kglab/tree/morph-kgc>

- moved example notebook to 2.1, along with other discussion about imports and serialization
- resolved pylint/mypy warnings
- added changenotes
- bumped version to 0.4.4

**Pull request merged**
